name: 'Lint and Testing'

on:
  'pull_request':
    branches: [main]
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 'install dependencies'
      run: npm ci

      - name: 'Run eslint'
      run: npm run lint

      - name: 'Run Tests'
      run: npm run test

